export const GET_TOP_HEADLINES = "GET_TOP_HEADLINES";
export const GET_BUSINESS_HEADLINES = "GET_BUSINESS_HEADLINES";
export const GET_ENTERTAINMENT_HEADLINES = "GET_ENTERTAINMENT_HEADLINES";
export const GET_HEALTH_HEADLINES = "GET_HEALTH_HEADLINES";
export const GET_SCIENCE_HEADLINES = "GET_SCIENCE_HEADLINES";
export const GET_SPORTS_HEADLINES = "GET_SPORTS_HEADLINES";
export const GET_TECHNOLOGY_HEADLINES = "GET_TECHNOLOGY_HEADLINES";

export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";
